import { useCallback, useEffect, useRef, useState } from "react";
import { Camera, CameraOff, Mic, MicOff, Phone, PhoneOff, Send, Users, X, Minimize2, Maximize2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const BASE = import.meta.env.BASE_URL?.replace(/\/$/, "") || "";
type Admin={adminId:string;adminName:string}; type Message={id?:number;senderId:string;senderName:string;message:string;conversationId:string;createdAt:string;reactions:Record<string,string[]>;clientMessageId?:string};
const initials=(s:string)=>s.slice(0,2).toUpperCase();
const dm=(a:string,b:string)=>`dm:${[a,b].sort((x,y)=>Number(x)-Number(y)).join(":")}`;

export default function AdminChatPage() {
  const {toast}=useToast(); const [me,setMe]=useState<Admin|null>(null); const [admins,setAdmins]=useState<Admin[]>([]);
  const [online,setOnline]=useState<Admin[]>([]); const [conversation,setConversation]=useState("group"); const [messages,setMessages]=useState<Message[]>([]);
  const [text,setText]=useState(""); const [typing,setTyping]=useState<string[]>([]); const [unread,setUnread]=useState<Record<string,number>>({}); const [mobileList,setMobileList]=useState(true);
  const [room,setRoom]=useState<string|null>(null); const [members,setMembers]=useState<string[]>([]); const [minimized,setMinimized]=useState(false); const [muted,setMuted]=useState(false); const [camera,setCamera]=useState(false);
  const device=useRef(crypto.randomUUID()), es=useRef<EventSource|null>(null), stream=useRef<MediaStream|null>(null), pcs=useRef(new Map<string,RTCPeerConnection>()), videos=useRef(new Map<string,MediaStream>()), [remote,setRemote]=useState<Record<string,MediaStream>>({});
  const localVideo=useRef<HTMLVideoElement>(null); const ice=useRef<RTCIceServer[]>([{urls:"stun:stun.l.google.com:19302"}]);
  const load=useCallback(async(id:string)=>{const r=await fetch(`${BASE}/api/admin/chat/messages?conversationId=${encodeURIComponent(id)}`,{credentials:"include"});if(r.ok)setMessages(await r.json());},[]);
  useEffect(()=>{fetch(`${BASE}/api/admin/chat/conversations`,{credentials:"include"}).then(r=>r.ok?r.json():null).then(d=>{if(d){setMe({adminId:d.me.id,adminName:d.me.name});setAdmins(d.admins);}});fetch(`${BASE}/api/admin/chat/ice-config`,{credentials:"include"}).then(r=>r.json()).then(d=>{if(d.iceServers)ice.current=d.iceServers}).catch(()=>{});},[]);
  useEffect(()=>{const invited=new URLSearchParams(window.location.search).get("room");if(invited)setRoom(invited);},[]);
  useEffect(()=>{load(conversation);setTyping([]);},[conversation,load]);
  const closeRoom=useCallback(async()=>{const id=room; for(const pc of pcs.current.values())pc.close();pcs.current.clear();stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRemote({});setRoom(null);setMembers([]);if(id)fetch(`${BASE}/api/admin/chat/rooms/${id}/leave`,{method:"POST",credentials:"include"}).catch(()=>{});},[room]);
  const sendSignal=useCallback((id:string,to:string,signal:any)=>fetch(`${BASE}/api/admin/chat/rooms/${id}/signal`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({to,signal})}),[]);
  const peer=useCallback(async(peerId:string,id:string,offer:boolean)=>{
    if(!stream.current)return; const pc=new RTCPeerConnection({iceServers:ice.current});pcs.current.set(peerId,pc);stream.current.getTracks().forEach(t=>pc.addTrack(t,stream.current!));
    pc.onicecandidate=e=>{if(e.candidate)sendSignal(id,peerId,{type:"ice",candidate:e.candidate}).catch(()=>{})};
    pc.ontrack=e=>{const s=e.streams[0]||new MediaStream([e.track]);videos.current.set(peerId,s);setRemote(Object.fromEntries(videos.current));};
    pc.onconnectionstatechange=()=>{if(["failed","closed"].includes(pc.connectionState)){pcs.current.delete(peerId);videos.current.delete(peerId);setRemote(Object.fromEntries(videos.current));}};
    if(offer){const o=await pc.createOffer();await pc.setLocalDescription(o);await sendSignal(id,peerId,{type:"offer",offer:o});} return pc;
  },[sendSignal]);
  useEffect(()=>{if(!me)return;const source=new EventSource(`${BASE}/api/admin/chat/stream?deviceId=${device.current}`,{withCredentials:true});es.current=source;source.onmessage=async e=>{const d=JSON.parse(e.data);
    if(d.type==="PRESENCE")setOnline(d.onlineAdmins||[]);
    if(d.type==="MESSAGE"){if(d.message.conversationId===conversation)setMessages(p=>p.some(x=>x.id===d.message.id)?p:[...p,d.message]);else setUnread(p=>({...p,[d.message.conversationId]:(p[d.message.conversationId]||0)+1}));}
    if(d.type==="REACTION"&&d.conversationId===conversation)setMessages(p=>p.map(x=>x.id===d.messageId?{...x,reactions:d.reactions}:x));
    if(d.type==="TYPING"&&d.conversationId===conversation&&d.adminId!==me.adminId)setTyping(p=>d.typing?[...new Set([...p,d.adminName])]:p.filter(x=>x!==d.adminName));
    if(d.type==="ROOM_INVITE"){toast({title:`Call from ${d.from.name}`,description:"Join the team room from the call bar."});setRoom(d.roomId);setMembers([]);}
    if(d.type==="ROOM_MEMBERS"&&d.roomId===room){setMembers(d.members);for(const member of d.members)if(member!==me.adminId&&Number(me.adminId)<Number(member)&&!pcs.current.has(member)&&stream.current)peer(member,d.roomId,true).catch(()=>{});}
    if(d.type==="ROOM_SIGNAL"&&d.roomId===room){let pc=pcs.current.get(d.from);if(d.signal.type==="offer"){pc=await peer(d.from,room!,false);await pc!.setRemoteDescription(d.signal.offer);const answer=await pc!.createAnswer();await pc!.setLocalDescription(answer);await sendSignal(room!,d.from,{type:"answer",answer});}else if(pc&&d.signal.type==="answer")await pc.setRemoteDescription(d.signal.answer);else if(pc&&d.signal.type==="ice")await pc.addIceCandidate(d.signal.candidate).catch(()=>{});}
  };return()=>source.close()},[me,conversation,room,peer,sendSignal,toast]);
  useEffect(()=>()=>{closeRoom();},[closeRoom]);
  const select=(id:string)=>{setConversation(id);setUnread(p=>{const next={...p};delete next[id];return next});setMobileList(false)};
  const send=async()=>{if(!text.trim()||!me)return;const body={message:text,conversationId:conversation,clientMessageId:crypto.randomUUID()};setText("");const r=await fetch(`${BASE}/api/admin/chat/messages`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)toast({title:"Message not sent",variant:"destructive"});};
  const typingPost=(active:boolean)=>fetch(`${BASE}/api/admin/chat/typing`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({typing:active,conversationId:conversation})}).catch(()=>{});
  const react=async(id:number,emoji:string)=>{const r=await fetch(`${BASE}/api/admin/chat/messages/${id}/react`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({emoji})});if(!r.ok)toast({title:"Reaction could not be saved",variant:"destructive"});};
  const join=async(id:string,withVideo=camera)=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:withVideo?{width:{ideal:1280}}:false});stream.current=s;if(localVideo.current)localVideo.current.srcObject=s;setRoom(id);const r=await fetch(`${BASE}/api/admin/chat/rooms/${id}/join`,{method:"POST",credentials:"include"});if(!r.ok)throw new Error("The room has ended");const d=await r.json();setMembers(d.members);for(const x of d.members)if(x!==me?.adminId&&Number(me?.adminId)<Number(x))await peer(x,id,true);}catch(e){toast({title:"Unable to join call",description:e instanceof Error?e.message:"Allow microphone access.",variant:"destructive"});setRoom(null);}};
  const start=async()=>{const r=await fetch(`${BASE}/api/admin/chat/rooms`,{method:"POST",credentials:"include"});if(!r.ok){toast({title:"Could not start call",variant:"destructive"});return;}const d=await r.json();await join(d.roomId,true);};
  const directName=(id:string)=>admins.find(a=>a.adminId!==(me?.adminId) && id.includes(`:${a.adminId}`))?.adminName||"Direct message";
  return <main className="h-[calc(100dvh-5rem)] min-h-0 bg-[#0b141a] text-white flex overflow-hidden rounded-xl" aria-label="Admin team chat">
    <aside className={`${mobileList?"flex":"hidden"} md:flex w-full md:w-80 shrink-0 flex-col border-r border-white/10 bg-[#111b21]`}><header className="p-4 font-bold flex items-center gap-2"><Users/> Team conversations</header><button onClick={()=>select("group")} className={`p-4 text-left ${conversation==="group"?"bg-[#202c33]":""}`}># Admin team <span className="text-xs text-emerald-400">{online.length} online</span>{unread.group?<span className="ml-2 rounded-full bg-emerald-500 px-1.5 text-[10px]">{unread.group}</span>:null}</button><div className="px-4 pt-3 text-xs uppercase text-slate-400">Direct messages</div>{admins.filter(a=>a.adminId!==me?.adminId).map(a=>{const id=dm(me!.adminId,a.adminId);return <button key={a.adminId} onClick={()=>select(id)} className={`p-4 text-left flex gap-3 ${conversation===id?"bg-[#202c33]":""}`}><span className="rounded-full bg-orange-500 w-9 h-9 grid place-items-center">{initials(a.adminName)}</span><span>{a.adminName}{unread[id]?<span className="ml-2 rounded-full bg-emerald-500 px-1.5 text-[10px]">{unread[id]}</span>:null}<small className="block text-slate-400">{online.some(x=>x.adminId===a.adminId)?"Connected":"Not currently connected"}</small></span></button>})}</aside>
    <section className={`${mobileList?"hidden":"flex"} md:flex flex-1 flex-col min-w-0`}><header className="h-16 px-4 flex items-center gap-3 bg-[#202c33]"><button className="md:hidden" onClick={()=>setMobileList(true)} aria-label="Back to conversations">‹</button><b>{conversation==="group"?"# Admin team":directName(conversation)}</b><button onClick={start} className="ml-auto p-2 rounded-full hover:bg-white/10" aria-label="Start team call"><Phone/></button></header><div className="flex-1 overflow-auto p-4 space-y-3 bg-[#0b141a]">{messages.map(m=><article key={m.id||m.clientMessageId} className={`max-w-[80%] rounded-lg p-3 ${m.senderId===me?.adminId?"ml-auto bg-[#005c4b]":"bg-[#202c33]"}`}><b className="text-xs text-orange-300">{m.senderName}</b><p>{m.message}</p><time className="text-[10px] text-slate-300">{new Date(m.createdAt).toLocaleTimeString()}</time><div>{Object.entries(m.reactions).map(([e,ids])=><span key={e}>{e} {ids.length}</span>)}{m.id?<button onClick={()=>react(m.id!,"👍")} className="ml-2 text-xs text-slate-300 hover:text-white" aria-label="React with thumbs up">👍</button>:null}</div></article>)}{typing.length>0&&<p className="text-xs text-slate-400">{typing.join(", ")} typing…</p>}</div><form onSubmit={e=>{e.preventDefault();send()}} className="p-3 flex gap-2 bg-[#202c33]"><input aria-label="Message" value={text} onChange={e=>{setText(e.target.value);typingPost(true)}} onBlur={()=>typingPost(false)} className="flex-1 rounded-full px-4 py-2 text-black" placeholder="Type a message"/><button aria-label="Send message" className="p-2 text-emerald-400"><Send/></button></form></section>
    {room&&<div className={`fixed z-50 bg-[#111b21] border border-white/15 shadow-2xl ${minimized?"bottom-4 right-4 w-72":"inset-4 md:inset-12"} rounded-xl p-3`}><header className="flex gap-2 items-center"><b>Team call · {members.length} participant{members.length===1?"":"s"}</b>{!stream.current&&<button onClick={()=>join(room)} className="bg-emerald-600 px-3 py-1 rounded">Join</button>}<button className="ml-auto" onClick={()=>setMinimized(x=>!x)} aria-label="Minimize call">{minimized?<Maximize2/>:<Minimize2/>}</button><button onClick={closeRoom} aria-label="Leave call"><X/></button></header>{!minimized&&stream.current&&<div className="grid grid-cols-2 md:grid-cols-3 gap-3 h-[calc(100%-4rem)] py-3"><video ref={localVideo} autoPlay muted playsInline className="w-full bg-black rounded-lg"/>{Object.entries(remote).map(([id,s])=><video key={id} autoPlay playsInline ref={v=>{if(v)v.srcObject=s}} className="w-full bg-black rounded-lg"/>)}</div>}<footer className="flex justify-center gap-3"><button onClick={()=>{stream.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(x=>!x)}} aria-label="Toggle microphone">{muted?<MicOff/>:<Mic/>}</button><button onClick={()=>toast({title:"Camera can be chosen before joining; restart the room to add it."})} aria-label="Toggle camera">{camera?<Camera/>:<CameraOff/>}</button><button onClick={closeRoom} className="text-red-400" aria-label="Leave call"><PhoneOff/></button></footer></div>}
  </main>;
}