const colors = {
  dark: {
    text: '#fafafa',
    tint: '#ff6600',
    background: '#000000',
    foreground: '#fafafa',
    card: '#0f0f0f',
    cardBorder: '#1e1e1e',
    cardForeground: '#fafafa',
    primary: '#ff6600',
    primaryForeground: '#ffffff',
    secondary: '#1a1a1a',
    secondaryForeground: '#fafafa',
    muted: '#141414',
    mutedForeground: '#a0a0a0',
    accent: '#ffc200',
    accentForeground: '#0a0a0a',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#252525',
    input: '#1a1a1a',
    ring: '#ff6600',
  },
  // Use dark for all — app is always dark themed
  light: {
    text: '#fafafa',
    tint: '#ff6600',
    background: '#000000',
    foreground: '#fafafa',
    card: '#0f0f0f',
    cardBorder: '#1e1e1e',
    cardForeground: '#fafafa',
    primary: '#ff6600',
    primaryForeground: '#ffffff',
    secondary: '#1a1a1a',
    secondaryForeground: '#fafafa',
    muted: '#141414',
    mutedForeground: '#a0a0a0',
    accent: '#ffc200',
    accentForeground: '#0a0a0a',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#252525',
    input: '#1a1a1a',
    ring: '#ff6600',
  },
  radius: 12,
};

export default colors;
